'use strict';

/**
 * activity enum
 *
 * ****WARNING****  This file is auto-generated!  Do NOT edit this file.
 */

const BaseType = require('../type');

module.exports = class Activity extends BaseType {
	static getValues() {
		return {
			0: 'manual',
			1: 'auto_multi_sport'
		};
	}
}
