'use strict';

/**
 * activity_level enum
 *
 * ****WARNING**** This file is auto-generated! Do NOT edit this file.
 */

const BaseType = require('../type');
const FieldTypes = require('../fieldTypes');

const ValuesMap = {
	0: 'low',
	1: 'medium',
	2: 'high'
};

class ActivityLevel extends BaseType {
	static getValues() {
		return ValuesMap;
	}

	static getSourceType() {
		return FieldTypes.Enum;
	}
};

module.exports = ActivityLevel;

ActivityLevel.Low = 0;
ActivityLevel.Medium = 1;
ActivityLevel.High = 2;
