'use strict';

/**
 * activity enum
 *
 * ****WARNING**** This file is auto-generated! Do NOT edit this file.
 */

const BaseType = require('../type');
const FieldTypes = require('../fieldTypes');

const ValuesMap = {
	0: 'manual',
	1: 'auto_multi_sport'
};

class Activity extends BaseType {
	static getValues() {
		return ValuesMap;
	}

	static getSourceType() {
		return FieldTypes.Enum;
	}
};

module.exports = Activity;

Activity.Manual = 0;
Activity.AutoMultiSport = 1;