'use strict';

/**
 * activity_subtype enum
 *
 * ****WARNING**** This file is auto-generated! Do NOT edit this file.
 */

const BaseType = require('../type');
const FieldTypes = require('../fieldTypes');

const ValuesMap = {
	0: 'generic',
	1: 'treadmill',       // Run
	2: 'street',          // Run
	3: 'trail',           // Run
	4: 'track',           // Run
	5: 'spin',            // Cycling
	6: 'indoor_cycling',  // Cycling
	7: 'road',            // Cycling
	8: 'mountain',        // Cycling
	9: 'downhill',        // Cycling
	10: 'recumbent',      // Cycling
	11: 'cyclocross',     // Cycling
	12: 'hand_cycling',   // Cycling
	13: 'track_cycling',  // Cycling
	14: 'indoor_rowing',  // Fitness Equipment
	15: 'elliptical',     // Fitness Equipment
	16: 'stair_climbing', // Fitness Equipment
	17: 'lap_swimming',   // Swimming
	18: 'open_water',     // Swimming
	254: 'all'
};

class ActivitySubtype extends BaseType {
	static getValues() {
		return ValuesMap;
	}

	static getSourceType() {
		return FieldTypes.Enum;
	}
};

module.exports = ActivitySubtype;

ActivitySubtype.Generic = 0;
ActivitySubtype.Treadmill = 1;
ActivitySubtype.Street = 2;
ActivitySubtype.Trail = 3;
ActivitySubtype.Track = 4;
ActivitySubtype.Spin = 5;
ActivitySubtype.IndoorCycling = 6;
ActivitySubtype.Road = 7;
ActivitySubtype.Mountain = 8;
ActivitySubtype.Downhill = 9;
ActivitySubtype.Recumbent = 10;
ActivitySubtype.Cyclocross = 11;
ActivitySubtype.HandCycling = 12;
ActivitySubtype.TrackCycling = 13;
ActivitySubtype.IndoorRowing = 14;
ActivitySubtype.Elliptical = 15;
ActivitySubtype.StairClimbing = 16;
ActivitySubtype.LapSwimming = 17;
ActivitySubtype.OpenWater = 18;
ActivitySubtype.All = 254;
