'use strict';

/**
 * activity_class enum
 *
 * ****WARNING**** This file is auto-generated! Do NOT edit this file.
 */

const BaseType = require('../type');
const FieldTypes = require('../fieldTypes');

const ValuesMap = {
	127: 'level',     // 0 to 100
	100: 'level_max',
	128: 'athlete'
};

class ActivityClass extends BaseType {
	static getValues() {
		return ValuesMap;
	}

	static getSourceType() {
		return FieldTypes.Enum;
	}
};

module.exports = ActivityClass;

ActivityClass.Level = 127;
ActivityClass.LevelMax = 100;
ActivityClass.Athlete = 128;
