'use strict';

/**
 * activity_type enum
 *
 * ****WARNING**** This file is auto-generated! Do NOT edit this file.
 */

const BaseType = require('../type');
const FieldTypes = require('../fieldTypes');

const ValuesMap = {
	0: 'generic',
	1: 'running',
	2: 'cycling',
	3: 'transition',        // Mulitsport transition
	4: 'fitness_equipment',
	5: 'swimming',
	6: 'walking',
	254: 'all'              // All is for goals only to include all sports.
};

class ActivityType extends BaseType {
	static getValues() {
		return ValuesMap;
	}

	static getSourceType() {
		return FieldTypes.Enum;
	}
};

module.exports = ActivityType;

ActivityType.Generic = 0;
ActivityType.Running = 1;
ActivityType.Cycling = 2;
ActivityType.Transition = 3;
ActivityType.FitnessEquipment = 4;
ActivityType.Swimming = 5;
ActivityType.Walking = 6;
ActivityType.All = 254;
