'use strict';

/**
 * activity_level enum
 *
 * ****WARNING****  This file is auto-generated!  Do NOT edit this file.
 */

const BaseType = require('../type');

const ValuesMap = {
	0: 'low',
	1: 'medium',
	2: 'high'
};

module.exports = class ActivityLevel extends BaseType {
	static getValues() {
		return ValuesMap;
	}
};
