'use strict';

/**
 * activity_level enum
 *
 * ****WARNING****  This file is auto-generated!  Do NOT edit this file.
 */

const BaseType = require('../type');

module.exports = class ActivityLevel extends BaseType {
	static getValues() {
		return {
			0: 'low',
			1: 'medium',
			2: 'high'
		};
	}
}
