'use strict';

/**
 * ant_network enum
 *
 * ****WARNING****  This file is auto-generated!  Do NOT edit this file.
 */

const BaseType = require('../type');

module.exports = class AntNetwork extends BaseType {
	static getValues() {
		return {
			0: 'public',
			1: 'antplus',
			2: 'antfs',
			3: 'private'
		};
	}
}
