'use strict';

/**
 * attitude_stage enum
 *
 * ****WARNING**** This file is auto-generated! Do NOT edit this file.
 */

const BaseType = require('../type');
const FieldTypes = require('../fieldTypes');

const ValuesMap = {
	0: 'failed',
	1: 'aligning',
	2: 'degraded',
	3: 'valid'
};

class AttitudeStage extends BaseType {
	static getValues() {
		return ValuesMap;
	}

	static getSourceType() {
		return FieldTypes.Enum;
	}
};

module.exports = AttitudeStage;

AttitudeStage.Failed = 0;
AttitudeStage.Aligning = 1;
AttitudeStage.Degraded = 2;
AttitudeStage.Valid = 3;
