'use strict';

/**
 * attitude_stage enum
 *
 * ****WARNING****  This file is auto-generated!  Do NOT edit this file.
 */
module.exports = {
	0: 'failed',
	1: 'aligning',
	2: 'degraded',
	3: 'valid'
};
