'use strict';

/**
 * autolap_trigger enum
 *
 * ****WARNING****  This file is auto-generated!  Do NOT edit this file.
 */
module.exports = {
	0: 'time',
	1: 'distance',
	2: 'position_start',
	3: 'position_lap',
	4: 'position_waypoint',
	5: 'position_marked',
	6: 'off'
};
