'use strict';

/**
 * battery_status uint8
 *
 * ****WARNING**** This file is auto-generated! Do NOT edit this file.
 */

const BaseType = require('../type');
const FieldTypes = require('../fieldTypes');

const ValuesMap = {
	1: 'new',
	2: 'good',
	3: 'ok',
	4: 'low',
	5: 'critical',
	7: 'unknown'
};

class BatteryStatus extends BaseType {
	static getValues() {
		return ValuesMap;
	}

	static getSourceType() {
		return FieldTypes.UInt8;
	}
};

module.exports = BatteryStatus;

