'use strict';

/**
 * body_location enum
 *
 * ****WARNING****  This file is auto-generated!  Do NOT edit this file.
 */

const BaseType = require('../type');
const FieldTypes = require('../fieldTypes');

const ValuesMap = {
	0: 'left_leg',
	1: 'left_calf',
	2: 'left_shin',
	3: 'left_hamstring',
	4: 'left_quad',
	5: 'left_glute',
	6: 'right_leg',
	7: 'right_calf',
	8: 'right_shin',
	9: 'right_hamstring',
	10: 'right_quad',
	11: 'right_glute',
	12: 'torso_back',
	13: 'left_lower_back',
	14: 'left_upper_back',
	15: 'right_lower_back',
	16: 'right_upper_back',
	17: 'torso_front',
	18: 'left_abdomen',
	19: 'left_chest',
	20: 'right_abdomen',
	21: 'right_chest',
	22: 'left_arm',
	23: 'left_shoulder',
	24: 'left_bicep',
	25: 'left_tricep',
	26: 'left_brachioradialis',    // Left anterior forearm
	27: 'left_forearm_extensors',  // Left posterior forearm
	28: 'right_arm',
	29: 'right_shoulder',
	30: 'right_bicep',
	31: 'right_tricep',
	32: 'right_brachioradialis',   // Right anterior forearm
	33: 'right_forearm_extensors', // Right posterior forearm
	34: 'neck',
	35: 'throat'
};

module.exports = class BodyLocation extends BaseType {
	static getValues() {
		return ValuesMap;
	}

	static getSourceType() {
		return FieldTypes.Enum;
	}
};
