'use strict';

/**
 * body_location enum
 *
 * ****WARNING**** This file is auto-generated! Do NOT edit this file.
 */

const BaseType = require('../type');
const FieldTypes = require('../fieldTypes');

const ValuesMap = {
	0: 'left_leg',
	1: 'left_calf',
	2: 'left_shin',
	3: 'left_hamstring',
	4: 'left_quad',
	5: 'left_glute',
	6: 'right_leg',
	7: 'right_calf',
	8: 'right_shin',
	9: 'right_hamstring',
	10: 'right_quad',
	11: 'right_glute',
	12: 'torso_back',
	13: 'left_lower_back',
	14: 'left_upper_back',
	15: 'right_lower_back',
	16: 'right_upper_back',
	17: 'torso_front',
	18: 'left_abdomen',
	19: 'left_chest',
	20: 'right_abdomen',
	21: 'right_chest',
	22: 'left_arm',
	23: 'left_shoulder',
	24: 'left_bicep',
	25: 'left_tricep',
	26: 'left_brachioradialis',    // Left anterior forearm
	27: 'left_forearm_extensors',  // Left posterior forearm
	28: 'right_arm',
	29: 'right_shoulder',
	30: 'right_bicep',
	31: 'right_tricep',
	32: 'right_brachioradialis',   // Right anterior forearm
	33: 'right_forearm_extensors', // Right posterior forearm
	34: 'neck',
	35: 'throat'
};

class BodyLocation extends BaseType {
	static getValues() {
		return ValuesMap;
	}

	static getSourceType() {
		return FieldTypes.Enum;
	}
};

module.exports = BodyLocation;

BodyLocation.LeftLeg = 0;
BodyLocation.LeftCalf = 1;
BodyLocation.LeftShin = 2;
BodyLocation.LeftHamstring = 3;
BodyLocation.LeftQuad = 4;
BodyLocation.LeftGlute = 5;
BodyLocation.RightLeg = 6;
BodyLocation.RightCalf = 7;
BodyLocation.RightShin = 8;
BodyLocation.RightHamstring = 9;
BodyLocation.RightQuad = 10;
BodyLocation.RightGlute = 11;
BodyLocation.TorsoBack = 12;
BodyLocation.LeftLowerBack = 13;
BodyLocation.LeftUpperBack = 14;
BodyLocation.RightLowerBack = 15;
BodyLocation.RightUpperBack = 16;
BodyLocation.TorsoFront = 17;
BodyLocation.LeftAbdomen = 18;
BodyLocation.LeftChest = 19;
BodyLocation.RightAbdomen = 20;
BodyLocation.RightChest = 21;
BodyLocation.LeftArm = 22;
BodyLocation.LeftShoulder = 23;
BodyLocation.LeftBicep = 24;
BodyLocation.LeftTricep = 25;
BodyLocation.LeftBrachioradialis = 26;
BodyLocation.LeftForearmExtensors = 27;
BodyLocation.RightArm = 28;
BodyLocation.RightShoulder = 29;
BodyLocation.RightBicep = 30;
BodyLocation.RightTricep = 31;
BodyLocation.RightBrachioradialis = 32;
BodyLocation.RightForearmExtensors = 33;
BodyLocation.Neck = 34;
BodyLocation.Throat = 35;