'use strict';

/**
 * camera_orientation_type enum
 *
 * ****WARNING****  This file is auto-generated!  Do NOT edit this file.
 */
module.exports = {
	0: 'camera_orientation_0',
	1: 'camera_orientation_90',
	2: 'camera_orientation_180',
	3: 'camera_orientation_270'
};
