'use strict';

/**
 * camera_orientation_type enum
 *
 * ****WARNING****  This file is auto-generated!  Do NOT edit this file.
 */

const BaseType = require('../type');
const FieldTypes = require('../fieldTypes');

const ValuesMap = {
	0: 'camera_orientation_0',
	1: 'camera_orientation_90',
	2: 'camera_orientation_180',
	3: 'camera_orientation_270'
};

module.exports = class CameraOrientationType extends BaseType {
	static getValues() {
		return ValuesMap;
	}

	static getSourceType() {
		return FieldTypes.Enum;
	}
};
