'use strict';

/**
 * checksum uint8
 *
 * ****WARNING****  This file is auto-generated!  Do NOT edit this file.
 */
module.exports = {
	0: 'clear', // Allows clear of checksum for flash memory where can only write 1 to 0 without erasing sector.
	1: 'ok'     // Set to mark checksum as valid if computes to invalid values 0 or 0xFF.  Checksum can also be set to ok to save encoding computation time.
};
