'use strict';

/**
 * course_point enum
 *
 * ****WARNING**** This file is auto-generated! Do NOT edit this file.
 */

const BaseType = require('../type');
const FieldTypes = require('../fieldTypes');

const ValuesMap = {
	0: 'generic',
	1: 'summit',
	2: 'valley',
	3: 'water',
	4: 'food',
	5: 'danger',
	6: 'left',
	7: 'right',
	8: 'straight',
	9: 'first_aid',
	10: 'fourth_category',
	11: 'third_category',
	12: 'second_category',
	13: 'first_category',
	14: 'hors_category',
	15: 'sprint',
	16: 'left_fork',
	17: 'right_fork',
	18: 'middle_fork',
	19: 'slight_left',
	20: 'sharp_left',
	21: 'slight_right',
	22: 'sharp_right',
	23: 'u_turn'
};

class CoursePoint extends BaseType {
	static getValues() {
		return ValuesMap;
	}

	static getSourceType() {
		return FieldTypes.Enum;
	}
};

module.exports = CoursePoint;

CoursePoint.Generic = 0;
CoursePoint.Summit = 1;
CoursePoint.Valley = 2;
CoursePoint.Water = 3;
CoursePoint.Food = 4;
CoursePoint.Danger = 5;
CoursePoint.Left = 6;
CoursePoint.Right = 7;
CoursePoint.Straight = 8;
CoursePoint.FirstAid = 9;
CoursePoint.FourthCategory = 10;
CoursePoint.ThirdCategory = 11;
CoursePoint.SecondCategory = 12;
CoursePoint.FirstCategory = 13;
CoursePoint.HorsCategory = 14;
CoursePoint.Sprint = 15;
CoursePoint.LeftFork = 16;
CoursePoint.RightFork = 17;
CoursePoint.MiddleFork = 18;
CoursePoint.SlightLeft = 19;
CoursePoint.SharpLeft = 20;
CoursePoint.SlightRight = 21;
CoursePoint.SharpRight = 22;
CoursePoint.UTurn = 23;
