'use strict';

/**
 * device_index uint8
 *
 * ****WARNING****  This file is auto-generated!  Do NOT edit this file.
 */

const BaseType = require('../type');

module.exports = class DeviceIndex extends BaseType {
	static getValues() {
		return {
			0: 'creator'  // Creator of the file is always device index 0.
		};
	}
}
