'use strict';

/**
 * device_index uint8
 *
 * ****WARNING****  This file is auto-generated!  Do NOT edit this file.
 */

const BaseType = require('../type');

const ValuesMap = {
	0: 'creator'  // Creator of the file is always device index 0.
};

module.exports = class DeviceIndex extends BaseType {
	static getValues() {
		return ValuesMap;
	}
};
