'use strict';

/**
 * display_power enum
 *
 * ****WARNING****  This file is auto-generated!  Do NOT edit this file.
 */

const BaseType = require('../type');

module.exports = class DisplayPower extends BaseType {
	static getValues() {
		return {
			0: 'watts',
			1: 'percent_ftp'
		};
	}
}
