'use strict';

/**
 * display_measure enum
 *
 * ****WARNING****  This file is auto-generated!  Do NOT edit this file.
 */

const BaseType = require('../type');

module.exports = class DisplayMeasure extends BaseType {
	static getValues() {
		return {
			0: 'metric',
			1: 'statute'
		};
	}
}
