'use strict';

/**
 * display_power enum
 *
 * ****WARNING**** This file is auto-generated! Do NOT edit this file.
 */

const BaseType = require('../type');
const FieldTypes = require('../fieldTypes');

const ValuesMap = {
	0: 'watts',
	1: 'percent_ftp'
};

class DisplayPower extends BaseType {
	static getValues() {
		return ValuesMap;
	}

	static getSourceType() {
		return FieldTypes.Enum;
	}
};

module.exports = DisplayPower;

DisplayPower.Watts = 0;
DisplayPower.PercentFtp = 1;