'use strict';

/**
 * display_heart enum
 *
 * ****WARNING****  This file is auto-generated!  Do NOT edit this file.
 */

const BaseType = require('../type');

const ValuesMap = {
	0: 'bpm',
	1: 'max',
	2: 'reserve'
};

module.exports = class DisplayHeart extends BaseType {
	static getValues() {
		return ValuesMap;
	}
};
