'use strict';

/**
 * display_heart enum
 *
 * ****WARNING****  This file is auto-generated!  Do NOT edit this file.
 */

const BaseType = require('../type');

module.exports = class DisplayHeart extends BaseType {
	static getValues() {
		return {
			0: 'bpm',
			1: 'max',
			2: 'reserve'
		};
	}
}
