'use strict';

/**
 * display_position enum
 *
 * ****WARNING****  This file is auto-generated!  Do NOT edit this file.
 */

const BaseType = require('../type');

module.exports = class DisplayPosition extends BaseType {
	static getValues() {
		return {
			0: 'degree',                  // dd.dddddd
			1: 'degree_minute',           // dddmm.mmm
			2: 'degree_minute_second',    // dddmmss
			3: 'austrian_grid',           // Austrian Grid (BMN)
			4: 'british_grid',            // British National Grid
			5: 'dutch_grid',              // Dutch grid system
			6: 'hungarian_grid',          // Hungarian grid system
			7: 'finnish_grid',            // Finnish grid system Zone3 KKJ27
			8: 'german_grid',             // Gausss Krueger (German)
			9: 'icelandic_grid',          // Icelandic Grid
			10: 'indonesian_equatorial',  // Indonesian Equatorial LCO
			11: 'indonesian_irian',       // Indonesian Irian LCO
			12: 'indonesian_southern',    // Indonesian Southern LCO
			13: 'india_zone_0',           // India zone 0
			14: 'india_zone_IA',          // India zone IA
			15: 'india_zone_IB',          // India zone IB
			16: 'india_zone_IIA',         // India zone IIA
			17: 'india_zone_IIB',         // India zone IIB
			18: 'india_zone_IIIA',        // India zone IIIA
			19: 'india_zone_IIIB',        // India zone IIIB
			20: 'india_zone_IVA',         // India zone IVA
			21: 'india_zone_IVB',         // India zone IVB
			22: 'irish_transverse',       // Irish Transverse Mercator
			23: 'irish_grid',             // Irish Grid
			24: 'loran',                  // Loran TD
			25: 'maidenhead_grid',        // Maidenhead grid system
			26: 'mgrs_grid',              // MGRS grid system
			27: 'new_zealand_grid',       // New Zealand grid system
			28: 'new_zealand_transverse', // New Zealand Transverse Mercator
			29: 'qatar_grid',             // Qatar National Grid
			30: 'modified_swedish_grid',  // Modified RT-90 (Sweden)
			31: 'swedish_grid',           // RT-90 (Sweden)
			32: 'south_african_grid',     // South African Grid
			33: 'swiss_grid',             // Swiss CH-1903 grid
			34: 'taiwan_grid',            // Taiwan Grid
			35: 'united_states_grid',     // United States National Grid
			36: 'utm_ups_grid',           // UTM/UPS grid system
			37: 'west_malayan',           // West Malayan RSO
			38: 'borneo_rso',             // Borneo RSO
			39: 'estonian_grid',          // Estonian grid system
			40: 'latvian_grid',           // Latvian Transverse Mercator
			41: 'swedish_ref_99_grid'     // Reference Grid 99 TM (Swedish)
		};
	}
}
