'use strict';

/**
 * file_flags uint8z
 *
 * ****WARNING****  This file is auto-generated!  Do NOT edit this file.
 */

const BaseType = require('../type');

module.exports = class FileFlags extends BaseType {
	static getValues() {
		return {
			2: 'read',
			4: 'write',
			8: 'erase'
		};
	}
}
