'use strict';

/**
 * gender enum
 *
 * ****WARNING****  This file is auto-generated!  Do NOT edit this file.
 */

const BaseType = require('../type');

module.exports = class Gender extends BaseType {
	static getValues() {
		return {
			0: 'female',
			1: 'male'
		};
	}
}
