'use strict';

/**
 * goal_recurrence enum
 *
 * ****WARNING**** This file is auto-generated! Do NOT edit this file.
 */

const BaseType = require('../type');
const FieldTypes = require('../fieldTypes');

const ValuesMap = {
	0: 'off',
	1: 'daily',
	2: 'weekly',
	3: 'monthly',
	4: 'yearly',
	5: 'custom'
};

class GoalRecurrence extends BaseType {
	static getValues() {
		return ValuesMap;
	}

	static getSourceType() {
		return FieldTypes.Enum;
	}
};

module.exports = GoalRecurrence;

GoalRecurrence.Off = 0;
GoalRecurrence.Daily = 1;
GoalRecurrence.Weekly = 2;
GoalRecurrence.Monthly = 3;
GoalRecurrence.Yearly = 4;
GoalRecurrence.Custom = 5;
