'use strict';

/**
 * goal_recurrence enum
 *
 * ****WARNING****  This file is auto-generated!  Do NOT edit this file.
 */

const BaseType = require('../type');

const ValuesMap = {
	0: 'off',
	1: 'daily',
	2: 'weekly',
	3: 'monthly',
	4: 'yearly',
	5: 'custom'
};

module.exports = class GoalRecurrence extends BaseType {
	static getValues() {
		return ValuesMap;
	}
};
