'use strict';

/**
 * goal enum
 *
 * ****WARNING****  This file is auto-generated!  Do NOT edit this file.
 */

const BaseType = require('../type');

module.exports = class Goal extends BaseType {
	static getValues() {
		return {
			0: 'time',
			1: 'distance',
			2: 'calories',
			3: 'frequency',
			4: 'steps'
		};
	}
}
