'use strict';

/**
 * goal enum
 *
 * ****WARNING**** This file is auto-generated! Do NOT edit this file.
 */

const BaseType = require('../type');
const FieldTypes = require('../fieldTypes');

const ValuesMap = {
	0: 'time',
	1: 'distance',
	2: 'calories',
	3: 'frequency',
	4: 'steps'
};

class Goal extends BaseType {
	static getValues() {
		return ValuesMap;
	}

	static getSourceType() {
		return FieldTypes.Enum;
	}
};

module.exports = Goal;

Goal.Time = 0;
Goal.Distance = 1;
Goal.Calories = 2;
Goal.Frequency = 3;
Goal.Steps = 4;
