'use strict';

/**
 * goal_recurrence enum
 *
 * ****WARNING****  This file is auto-generated!  Do NOT edit this file.
 */
module.exports = {
	0: 'off',
	1: 'daily',
	2: 'weekly',
	3: 'monthly',
	4: 'yearly',
	5: 'custom'
};
