'use strict';

/**
 * hr_type enum
 *
 * ****WARNING****  This file is auto-generated!  Do NOT edit this file.
 */

const BaseType = require('../type');

module.exports = class HrType extends BaseType {
	static getValues() {
		return {
			0: 'normal',
			1: 'irregular'
		};
	}
}
