'use strict';

/**
 * hr_zone_calc enum
 *
 * ****WARNING****  This file is auto-generated!  Do NOT edit this file.
 */

const BaseType = require('../type');

module.exports = class HrZoneCalc extends BaseType {
	static getValues() {
		return {
			0: 'custom',
			1: 'percent_max_hr',
			2: 'percent_hrr'
		};
	}
}
