'use strict';

/**
 * intensity enum
 *
 * ****WARNING****  This file is auto-generated!  Do NOT edit this file.
 */

const BaseType = require('../type');

const ValuesMap = {
	0: 'active',
	1: 'rest',
	2: 'warmup',
	3: 'cooldown'
};

module.exports = class Intensity extends BaseType {
	static getValues() {
		return ValuesMap;
	}
};
