'use strict';

/**
 * intensity enum
 *
 * ****WARNING****  This file is auto-generated!  Do NOT edit this file.
 */

const BaseType = require('../type');

module.exports = class Intensity extends BaseType {
	static getValues() {
		return {
			0: 'active',
			1: 'rest',
			2: 'warmup',
			3: 'cooldown'
		};
	}
}
