'use strict';

/**
 * language enum
 *
 * ****WARNING**** This file is auto-generated! Do NOT edit this file.
 */

const BaseType = require('../type');
const FieldTypes = require('../fieldTypes');

const ValuesMap = {
	0: 'english',
	1: 'french',
	2: 'italian',
	3: 'german',
	4: 'spanish',
	5: 'croatian',
	6: 'czech',
	7: 'danish',
	8: 'dutch',
	9: 'finnish',
	10: 'greek',
	11: 'hungarian',
	12: 'norwegian',
	13: 'polish',
	14: 'portuguese',
	15: 'slovakian',
	16: 'slovenian',
	17: 'swedish',
	18: 'russian',
	19: 'turkish',
	20: 'latvian',
	21: 'ukrainian',
	22: 'arabic',
	23: 'farsi',
	24: 'bulgarian',
	25: 'romanian',
	254: 'custom'
};

class Language extends BaseType {
	static getValues() {
		return ValuesMap;
	}

	static getSourceType() {
		return FieldTypes.Enum;
	}
};

module.exports = Language;

Language.English = 0;
Language.French = 1;
Language.Italian = 2;
Language.German = 3;
Language.Spanish = 4;
Language.Croatian = 5;
Language.Czech = 6;
Language.Danish = 7;
Language.Dutch = 8;
Language.Finnish = 9;
Language.Greek = 10;
Language.Hungarian = 11;
Language.Norwegian = 12;
Language.Polish = 13;
Language.Portuguese = 14;
Language.Slovakian = 15;
Language.Slovenian = 16;
Language.Swedish = 17;
Language.Russian = 18;
Language.Turkish = 19;
Language.Latvian = 20;
Language.Ukrainian = 21;
Language.Arabic = 22;
Language.Farsi = 23;
Language.Bulgarian = 24;
Language.Romanian = 25;
Language.Custom = 254;