'use strict';

/**
 * lap_trigger enum
 *
 * ****WARNING****  This file is auto-generated!  Do NOT edit this file.
 */

const BaseType = require('../type');

module.exports = class LapTrigger extends BaseType {
	static getValues() {
		return {
			0: 'manual',
			1: 'time',
			2: 'distance',
			3: 'position_start',
			4: 'position_lap',
			5: 'position_waypoint',
			6: 'position_marked',
			7: 'session_end',
			8: 'fitness_equipment'
		};
	}
}
