'use strict';

/**
 * lap_trigger enum
 *
 * ****WARNING**** This file is auto-generated! Do NOT edit this file.
 */

const BaseType = require('../type');
const FieldTypes = require('../fieldTypes');

const ValuesMap = {
	0: 'manual',
	1: 'time',
	2: 'distance',
	3: 'position_start',
	4: 'position_lap',
	5: 'position_waypoint',
	6: 'position_marked',
	7: 'session_end',
	8: 'fitness_equipment'
};

class LapTrigger extends BaseType {
	static getValues() {
		return ValuesMap;
	}

	static getSourceType() {
		return FieldTypes.Enum;
	}
};

module.exports = LapTrigger;

LapTrigger.Manual = 0;
LapTrigger.Time = 1;
LapTrigger.Distance = 2;
LapTrigger.PositionStart = 3;
LapTrigger.PositionLap = 4;
LapTrigger.PositionWaypoint = 5;
LapTrigger.PositionMarked = 6;
LapTrigger.SessionEnd = 7;
LapTrigger.FitnessEquipment = 8;
