'use strict';

/**
 * left_right_balance_100 uint16
 *
 * ****WARNING****  This file is auto-generated!  Do NOT edit this file.
 */
module.exports = {
	16383: 'mask',  // % contribution scaled by 100
	32768: 'right'  // data corresponds to right if set, otherwise unknown
};
