'use strict';

/**
 * left_right_balance_100 uint16
 *
 * ****WARNING****  This file is auto-generated!  Do NOT edit this file.
 */

const BaseType = require('../type');

module.exports = class LeftRightBalance100 extends BaseType {
	static getValues() {
		return {
			16383: 'mask',  // % contribution scaled by 100
			32768: 'right'  // data corresponds to right if set, otherwise unknown
		};
	}
}
