'use strict';

/**
 * left_right_balance uint8
 *
 * ****WARNING**** This file is auto-generated! Do NOT edit this file.
 */

const BaseType = require('../type');
const FieldTypes = require('../fieldTypes');

const ValuesMap = {
	127: 'mask',  // % contribution
	128: 'right'  // data corresponds to right if set, otherwise unknown
};

class LeftRightBalance extends BaseType {
	static getValues() {
		return ValuesMap;
	}

	static getSourceType() {
		return FieldTypes.UInt8;
	}
};

module.exports = LeftRightBalance;

