'use strict';

/**
 * left_right_balance uint8
 *
 * ****WARNING****  This file is auto-generated!  Do NOT edit this file.
 */
module.exports = {
	127: 'mask',  // % contribution
	128: 'right'  // data corresponds to right if set, otherwise unknown
};
