'use strict';

/**
 * length_type enum
 *
 * ****WARNING**** This file is auto-generated! Do NOT edit this file.
 */

const BaseType = require('../type');
const FieldTypes = require('../fieldTypes');

const ValuesMap = {
	0: 'idle',   // Rest period. Length with no strokes
	1: 'active'  // Length with strokes.
};

class LengthType extends BaseType {
	static getValues() {
		return ValuesMap;
	}

	static getSourceType() {
		return FieldTypes.Enum;
	}
};

module.exports = LengthType;

LengthType.Idle = 0;
LengthType.Active = 1;
