'use strict';

/**
 * length_type enum
 *
 * ****WARNING****  This file is auto-generated!  Do NOT edit this file.
 */
module.exports = {
	0: 'idle',   // Rest period. Length with no strokes
	1: 'active'  // Length with strokes.
};
