'use strict';

/**
 * mesg_num uint16
 *
 * ****WARNING****  This file is auto-generated!  Do NOT edit this file.
 */

const BaseType = require('../type');

module.exports = class MesgNum extends BaseType {
	static getValues() {
		return {
			0: 'file_id',
			1: 'capabilities',
			2: 'device_settings',
			3: 'user_profile',
			4: 'hrm_profile',
			5: 'sdm_profile',
			6: 'bike_profile',
			7: 'zones_target',
			8: 'hr_zone',
			9: 'power_zone',
			10: 'met_zone',
			12: 'sport',
			15: 'goal',
			18: 'session',
			19: 'lap',
			20: 'record',
			21: 'event',
			23: 'device_info',
			26: 'workout',
			27: 'workout_step',
			28: 'schedule',
			30: 'weight_scale',
			31: 'course',
			32: 'course_point',
			33: 'totals',
			34: 'activity',
			35: 'software',
			37: 'file_capabilities',
			38: 'mesg_capabilities',
			39: 'field_capabilities',
			49: 'file_creator',
			51: 'blood_pressure',
			53: 'speed_zone',
			55: 'monitoring',
			72: 'training_file',
			78: 'hrv',
			101: 'length',
			103: 'monitoring_info',
			105: 'pad',
			106: 'slave_device',
			131: 'cadence_zone',
			142: 'segment_lap',
			145: 'memo_glob',
			148: 'segment_id',
			149: 'segment_leaderboard_entry',
			150: 'segment_point',
			151: 'segment_file',
			160: 'gps_metadata',
			161: 'camera_event',
			162: 'timestamp_correlation',
			164: 'gyroscope_data',
			165: 'accelerometer_data',
			167: 'three_d_sensor_calibration',
			169: 'video_frame',
			174: 'obdii_data',
			177: 'nmea_sentence',
			178: 'aviation_attitude',
			184: 'video',
			185: 'video_title',
			186: 'video_description',
			187: 'video_clip',
			65280: 'mfg_range_min',            // 0xFF00 - 0xFFFE reserved for manufacturer specific messages
			65534: 'mfg_range_max'             // 0xFF00 - 0xFFFE reserved for manufacturer specific messages
		};
	}
}
