'use strict';

/**
 * message_index uint16
 *
 * ****WARNING**** This file is auto-generated! Do NOT edit this file.
 */

const BaseType = require('../type');
const FieldTypes = require('../fieldTypes');

const ValuesMap = {
	32768: 'selected', // message is selected if set
	28672: 'reserved', // reserved (default 0)
	4095: 'mask'       // index
};

class MessageIndex extends BaseType {
	static getValues() {
		return ValuesMap;
	}

	static getSourceType() {
		return FieldTypes.UInt16;
	}
};

module.exports = MessageIndex;
