'use strict';

/**
 * pwr_zone_calc enum
 *
 * ****WARNING**** This file is auto-generated! Do NOT edit this file.
 */

const BaseType = require('../type');
const FieldTypes = require('../fieldTypes');

const ValuesMap = {
	0: 'custom',
	1: 'percent_ftp'
};

class PwrZoneCalc extends BaseType {
	static getValues() {
		return ValuesMap;
	}

	static getSourceType() {
		return FieldTypes.Enum;
	}
};

module.exports = PwrZoneCalc;

PwrZoneCalc.Custom = 0;
PwrZoneCalc.PercentFtp = 1;
