'use strict';

/**
 * pwr_zone_calc enum
 *
 * ****WARNING****  This file is auto-generated!  Do NOT edit this file.
 */

const BaseType = require('../type');

const ValuesMap = {
	0: 'custom',
	1: 'percent_ftp'
};

module.exports = class PwrZoneCalc extends BaseType {
	static getValues() {
		return ValuesMap;
	}
};
