'use strict';

/**
 * rider_position_type enum
 *
 * ****WARNING**** This file is auto-generated! Do NOT edit this file.
 */

const BaseType = require('../type');
const FieldTypes = require('../fieldTypes');

const ValuesMap = {
	0: 'seated',
	1: 'standing'
};

class RiderPositionType extends BaseType {
	static getValues() {
		return ValuesMap;
	}

	static getSourceType() {
		return FieldTypes.Enum;
	}
};

module.exports = RiderPositionType;

RiderPositionType.Seated = 0;
RiderPositionType.Standing = 1;
