'use strict';

/**
 * rider_position_type enum
 *
 * ****WARNING****  This file is auto-generated!  Do NOT edit this file.
 */

const BaseType = require('../type');

const ValuesMap = {
	0: 'seated',
	1: 'standing'
};

module.exports = class RiderPositionType extends BaseType {
	static getValues() {
		return ValuesMap;
	}
};
