'use strict';

/**
 * schedule enum
 *
 * ****WARNING****  This file is auto-generated!  Do NOT edit this file.
 */

const BaseType = require('../type');

const ValuesMap = {
	0: 'workout',
	1: 'course'
};

module.exports = class Schedule extends BaseType {
	static getValues() {
		return ValuesMap;
	}
};
