'use strict';

/**
 * schedule enum
 *
 * ****WARNING**** This file is auto-generated! Do NOT edit this file.
 */

const BaseType = require('../type');
const FieldTypes = require('../fieldTypes');

const ValuesMap = {
	0: 'workout',
	1: 'course'
};

class Schedule extends BaseType {
	static getValues() {
		return ValuesMap;
	}

	static getSourceType() {
		return FieldTypes.Enum;
	}
};

module.exports = Schedule;

Schedule.Workout = 0;
Schedule.Course = 1;
