'use strict';

/**
 * schedule enum
 *
 * ****WARNING****  This file is auto-generated!  Do NOT edit this file.
 */

const BaseType = require('../type');

module.exports = class Schedule extends BaseType {
	static getValues() {
		return {
			0: 'workout',
			1: 'course'
		};
	}
}
