'use strict';

/**
 * segment_lap_status enum
 *
 * ****WARNING**** This file is auto-generated! Do NOT edit this file.
 */

const BaseType = require('../type');
const FieldTypes = require('../fieldTypes');

const ValuesMap = {
	0: 'end',
	1: 'fail'
};

class SegmentLapStatus extends BaseType {
	static getValues() {
		return ValuesMap;
	}

	static getSourceType() {
		return FieldTypes.Enum;
	}
};

module.exports = SegmentLapStatus;

SegmentLapStatus.End = 0;
SegmentLapStatus.Fail = 1;
