'use strict';

/**
 * segment_delete_status enum
 *
 * ****WARNING****  This file is auto-generated!  Do NOT edit this file.
 */

const BaseType = require('../type');

const ValuesMap = {
	0: 'do_not_delete',
	1: 'delete_one',
	2: 'delete_all'
};

module.exports = class SegmentDeleteStatus extends BaseType {
	static getValues() {
		return ValuesMap;
	}
};
