'use strict';

/**
 * segment_selection_type enum
 *
 * ****WARNING****  This file is auto-generated!  Do NOT edit this file.
 */

const BaseType = require('../type');

module.exports = class SegmentSelectionType extends BaseType {
	static getValues() {
		return {
			0: 'starred',
			1: 'suggested'
		};
	}
}
