'use strict';

/**
 * segment_leaderboard_type enum
 *
 * ****WARNING****  This file is auto-generated!  Do NOT edit this file.
 */
module.exports = {
	0: 'overall',
	1: 'personal_best',
	2: 'connections',
	3: 'group',
	4: 'challenger',
	5: 'kom',
	6: 'qom',
	7: 'pr',
	8: 'goal',
	9: 'rival',
	10: 'club_leader'
};
