'use strict';

/**
 * segment_lap_status enum
 *
 * ****WARNING****  This file is auto-generated!  Do NOT edit this file.
 */

const BaseType = require('../type');

module.exports = class SegmentLapStatus extends BaseType {
	static getValues() {
		return {
			0: 'end',
			1: 'fail'
		};
	}
}
