'use strict';

/**
 * sport_event enum
 *
 * ****WARNING**** This file is auto-generated! Do NOT edit this file.
 */

const BaseType = require('../type');
const FieldTypes = require('../fieldTypes');

const ValuesMap = {
	0: 'uncategorized',
	1: 'geocaching',
	2: 'fitness',
	3: 'recreation',
	4: 'race',
	5: 'special_event',
	6: 'training',
	7: 'transportation',
	8: 'touring'
};

class SportEvent extends BaseType {
	static getValues() {
		return ValuesMap;
	}

	static getSourceType() {
		return FieldTypes.Enum;
	}
};

module.exports = SportEvent;

SportEvent.Uncategorized = 0;
SportEvent.Geocaching = 1;
SportEvent.Fitness = 2;
SportEvent.Recreation = 3;
SportEvent.Race = 4;
SportEvent.SpecialEvent = 5;
SportEvent.Training = 6;
SportEvent.Transportation = 7;
SportEvent.Touring = 8;