'use strict';

/**
 * sport_bits_0 uint8z
 *
 * ****WARNING****  This file is auto-generated!  Do NOT edit this file.
 */
module.exports = {
	1: 'generic',
	2: 'running',
	4: 'cycling',
	8: 'transition',         // Mulitsport transition
	16: 'fitness_equipment',
	32: 'swimming',
	64: 'basketball',
	128: 'soccer'
};
