'use strict';

/**
 * sport_event enum
 *
 * ****WARNING****  This file is auto-generated!  Do NOT edit this file.
 */

const BaseType = require('../type');

const ValuesMap = {
	0: 'uncategorized',
	1: 'geocaching',
	2: 'fitness',
	3: 'recreation',
	4: 'race',
	5: 'special_event',
	6: 'training',
	7: 'transportation',
	8: 'touring'
};

module.exports = class SportEvent extends BaseType {
	static getValues() {
		return ValuesMap;
	}
};
