'use strict';

/**
 * sport_bits_1 uint8z
 *
 * ****WARNING**** This file is auto-generated! Do NOT edit this file.
 */

const BaseType = require('../type');
const FieldTypes = require('../fieldTypes');

const ValuesMap = {
	1: 'tennis',
	2: 'american_football',
	4: 'training',
	8: 'walking',
	16: 'cross_country_skiing',
	32: 'alpine_skiing',
	64: 'snowboarding',
	128: 'rowing'
};

class SportBits1 extends BaseType {
	static getValues() {
		return ValuesMap;
	}

	static getSourceType() {
		return FieldTypes.UInt8z;
	}
};

module.exports = SportBits1;

