'use strict';

/**
 * sport enum
 *
 * ****WARNING**** This file is auto-generated! Do NOT edit this file.
 */

const BaseType = require('../type');
const FieldTypes = require('../fieldTypes');

const ValuesMap = {
	0: 'generic',
	1: 'running',
	2: 'cycling',
	3: 'transition',               // Mulitsport transition
	4: 'fitness_equipment',
	5: 'swimming',
	6: 'basketball',
	7: 'soccer',
	8: 'tennis',
	9: 'american_football',
	10: 'training',
	11: 'walking',
	12: 'cross_country_skiing',
	13: 'alpine_skiing',
	14: 'snowboarding',
	15: 'rowing',
	16: 'mountaineering',
	17: 'hiking',
	18: 'multisport',
	19: 'paddling',
	20: 'flying',
	21: 'e_biking',
	22: 'motorcycling',
	23: 'boating',
	24: 'driving',
	25: 'golf',
	26: 'hang_gliding',
	27: 'horseback_riding',
	28: 'hunting',
	29: 'fishing',
	30: 'inline_skating',
	31: 'rock_climbing',
	32: 'sailing',
	33: 'ice_skating',
	34: 'sky_diving',
	35: 'snowshoeing',
	36: 'snowmobiling',
	37: 'stand_up_paddleboarding',
	38: 'surfing',
	39: 'wakeboarding',
	40: 'water_skiing',
	41: 'kayaking',
	42: 'rafting',
	43: 'windsurfing',
	44: 'kitesurfing',
	254: 'all'                     // All is for goals only to include all sports.
};

class Sport extends BaseType {
	static getValues() {
		return ValuesMap;
	}

	static getSourceType() {
		return FieldTypes.Enum;
	}
};

module.exports = Sport;

Sport.Generic = 0;
Sport.Running = 1;
Sport.Cycling = 2;
Sport.Transition = 3;
Sport.FitnessEquipment = 4;
Sport.Swimming = 5;
Sport.Basketball = 6;
Sport.Soccer = 7;
Sport.Tennis = 8;
Sport.AmericanFootball = 9;
Sport.Training = 10;
Sport.Walking = 11;
Sport.CrossCountrySkiing = 12;
Sport.AlpineSkiing = 13;
Sport.Snowboarding = 14;
Sport.Rowing = 15;
Sport.Mountaineering = 16;
Sport.Hiking = 17;
Sport.Multisport = 18;
Sport.Paddling = 19;
Sport.Flying = 20;
Sport.EBiking = 21;
Sport.Motorcycling = 22;
Sport.Boating = 23;
Sport.Driving = 24;
Sport.Golf = 25;
Sport.HangGliding = 26;
Sport.HorsebackRiding = 27;
Sport.Hunting = 28;
Sport.Fishing = 29;
Sport.InlineSkating = 30;
Sport.RockClimbing = 31;
Sport.Sailing = 32;
Sport.IceSkating = 33;
Sport.SkyDiving = 34;
Sport.Snowshoeing = 35;
Sport.Snowmobiling = 36;
Sport.StandUpPaddleboarding = 37;
Sport.Surfing = 38;
Sport.Wakeboarding = 39;
Sport.WaterSkiing = 40;
Sport.Kayaking = 41;
Sport.Rafting = 42;
Sport.Windsurfing = 43;
Sport.Kitesurfing = 44;
Sport.All = 254;
