'use strict';

/**
 * sport_bits_0 uint8z
 *
 * ****WARNING**** This file is auto-generated! Do NOT edit this file.
 */

const BaseType = require('../type');
const FieldTypes = require('../fieldTypes');

const ValuesMap = {
	1: 'generic',
	2: 'running',
	4: 'cycling',
	8: 'transition',         // Mulitsport transition
	16: 'fitness_equipment',
	32: 'swimming',
	64: 'basketball',
	128: 'soccer'
};

class SportBits0 extends BaseType {
	static getValues() {
		return ValuesMap;
	}

	static getSourceType() {
		return FieldTypes.UInt8z;
	}
};

module.exports = SportBits0;
