'use strict';

/**
 * sport_bits_2 uint8z
 *
 * ****WARNING****  This file is auto-generated!  Do NOT edit this file.
 */

const BaseType = require('../type');

module.exports = class SportBits2 extends BaseType {
	static getValues() {
		return {
			1: 'mountaineering',
			2: 'hiking',
			4: 'multisport',
			8: 'paddling',
			16: 'flying',
			32: 'e_biking',
			64: 'motorcycling',
			128: 'boating'
		};
	}
}
