'use strict';

/**
 * sport_bits_2 uint8z
 *
 * ****WARNING**** This file is auto-generated! Do NOT edit this file.
 */

const BaseType = require('../type');
const FieldTypes = require('../fieldTypes');

const ValuesMap = {
	1: 'mountaineering',
	2: 'hiking',
	4: 'multisport',
	8: 'paddling',
	16: 'flying',
	32: 'e_biking',
	64: 'motorcycling',
	128: 'boating'
};

class SportBits2 extends BaseType {
	static getValues() {
		return ValuesMap;
	}

	static getSourceType() {
		return FieldTypes.UInt8z;
	}
};

module.exports = SportBits2;
