'use strict';

/**
 * sport enum
 *
 * ****WARNING****  This file is auto-generated!  Do NOT edit this file.
 */

const BaseType = require('../type');

module.exports = class Sport extends BaseType {
	static getValues() {
		return {
			0: 'generic',
			1: 'running',
			2: 'cycling',
			3: 'transition',               // Mulitsport transition
			4: 'fitness_equipment',
			5: 'swimming',
			6: 'basketball',
			7: 'soccer',
			8: 'tennis',
			9: 'american_football',
			10: 'training',
			11: 'walking',
			12: 'cross_country_skiing',
			13: 'alpine_skiing',
			14: 'snowboarding',
			15: 'rowing',
			16: 'mountaineering',
			17: 'hiking',
			18: 'multisport',
			19: 'paddling',
			20: 'flying',
			21: 'e_biking',
			22: 'motorcycling',
			23: 'boating',
			24: 'driving',
			25: 'golf',
			26: 'hang_gliding',
			27: 'horseback_riding',
			28: 'hunting',
			29: 'fishing',
			30: 'inline_skating',
			31: 'rock_climbing',
			32: 'sailing',
			33: 'ice_skating',
			34: 'sky_diving',
			35: 'snowshoeing',
			36: 'snowmobiling',
			37: 'stand_up_paddleboarding',
			38: 'surfing',
			39: 'wakeboarding',
			40: 'water_skiing',
			41: 'kayaking',
			42: 'rafting',
			43: 'windsurfing',
			44: 'kitesurfing',
			254: 'all'                     // All is for goals only to include all sports.
		};
	}
}
