'use strict';

/**
 * sport_bits_3 uint8z
 *
 * ****WARNING****  This file is auto-generated!  Do NOT edit this file.
 */
module.exports = {
	1: 'driving',
	2: 'golf',
	4: 'hang_gliding',
	8: 'horseback_riding',
	16: 'hunting',
	32: 'fishing',
	64: 'inline_skating',
	128: 'rock_climbing'
};
