'use strict';

/**
 * sport_bits_4 uint8z
 *
 * ****WARNING****  This file is auto-generated!  Do NOT edit this file.
 */
module.exports = {
	1: 'sailing',
	2: 'ice_skating',
	4: 'sky_diving',
	8: 'snowshoeing',
	16: 'snowmobiling',
	32: 'stand_up_paddleboarding',
	64: 'surfing',
	128: 'wakeboarding'
};
