'use strict';

/**
 * sport_bits_5 uint8z
 *
 * ****WARNING****  This file is auto-generated!  Do NOT edit this file.
 */

const BaseType = require('../type');

const ValuesMap = {
	1: 'water_skiing',
	2: 'kayaking',
	4: 'rafting',
	8: 'windsurfing',
	16: 'kitesurfing'
};

module.exports = class SportBits5 extends BaseType {
	static getValues() {
		return ValuesMap;
	}
};
