'use strict';

/**
 * stroke_type enum
 *
 * ****WARNING****  This file is auto-generated!  Do NOT edit this file.
 */
module.exports = {
	0: 'no_event',
	1: 'other',    // stroke was detected but cannot be identified
	2: 'serve',
	3: 'forehand',
	4: 'backhand',
	5: 'smash'
};
