'use strict';

/**
 * stroke_type enum
 *
 * ****WARNING**** This file is auto-generated! Do NOT edit this file.
 */

const BaseType = require('../type');
const FieldTypes = require('../fieldTypes');

const ValuesMap = {
	0: 'no_event',
	1: 'other',    // stroke was detected but cannot be identified
	2: 'serve',
	3: 'forehand',
	4: 'backhand',
	5: 'smash'
};

class StrokeType extends BaseType {
	static getValues() {
		return ValuesMap;
	}

	static getSourceType() {
		return FieldTypes.Enum;
	}
};

module.exports = StrokeType;

StrokeType.NoEvent = 0;
StrokeType.Other = 1;
StrokeType.Serve = 2;
StrokeType.Forehand = 3;
StrokeType.Backhand = 4;
StrokeType.Smash = 5;
