'use strict';

/**
 * time_zone enum
 *
 * ****WARNING**** This file is auto-generated! Do NOT edit this file.
 */

const BaseType = require('../type');
const FieldTypes = require('../fieldTypes');

const ValuesMap = {
	0: 'almaty',
	1: 'bangkok',
	2: 'bombay',
	3: 'brasilia',
	4: 'cairo',
	5: 'cape_verde_is',
	6: 'darwin',
	7: 'eniwetok',
	8: 'fiji',
	9: 'hong_kong',
	10: 'islamabad',
	11: 'kabul',
	12: 'magadan',
	13: 'mid_atlantic',
	14: 'moscow',
	15: 'muscat',
	16: 'newfoundland',
	17: 'samoa',
	18: 'sydney',
	19: 'tehran',
	20: 'tokyo',
	21: 'us_alaska',
	22: 'us_atlantic',
	23: 'us_central',
	24: 'us_eastern',
	25: 'us_hawaii',
	26: 'us_mountain',
	27: 'us_pacific',
	28: 'other',
	29: 'auckland',
	30: 'kathmandu',
	31: 'europe_western_wet',
	32: 'europe_central_cet',
	33: 'europe_eastern_eet',
	34: 'jakarta',
	35: 'perth',
	36: 'adelaide',
	37: 'brisbane',
	38: 'tasmania',
	39: 'iceland',
	40: 'amsterdam',
	41: 'athens',
	42: 'barcelona',
	43: 'berlin',
	44: 'brussels',
	45: 'budapest',
	46: 'copenhagen',
	47: 'dublin',
	48: 'helsinki',
	49: 'lisbon',
	50: 'london',
	51: 'madrid',
	52: 'munich',
	53: 'oslo',
	54: 'paris',
	55: 'prague',
	56: 'reykjavik',
	57: 'rome',
	58: 'stockholm',
	59: 'vienna',
	60: 'warsaw',
	61: 'zurich',
	62: 'quebec',
	63: 'ontario',
	64: 'manitoba',
	65: 'saskatchewan',
	66: 'alberta',
	67: 'british_columbia',
	68: 'boise',
	69: 'boston',
	70: 'chicago',
	71: 'dallas',
	72: 'denver',
	73: 'kansas_city',
	74: 'las_vegas',
	75: 'los_angeles',
	76: 'miami',
	77: 'minneapolis',
	78: 'new_york',
	79: 'new_orleans',
	80: 'phoenix',
	81: 'santa_fe',
	82: 'seattle',
	83: 'washington_dc',
	84: 'us_arizona',
	85: 'chita',
	86: 'ekaterinburg',
	87: 'irkutsk',
	88: 'kaliningrad',
	89: 'krasnoyarsk',
	90: 'novosibirsk',
	91: 'petropavlovsk_kamchatskiy',
	92: 'samara',
	93: 'vladivostok',
	94: 'mexico_central',
	95: 'mexico_mountain',
	96: 'mexico_pacific',
	97: 'cape_town',
	98: 'winkhoek',
	99: 'lagos',
	100: 'riyahd',
	101: 'venezuela',
	102: 'australia_lh',
	103: 'santiago',
	253: 'manual',
	254: 'automatic'
};

class TimeZone extends BaseType {
	static getValues() {
		return ValuesMap;
	}

	static getSourceType() {
		return FieldTypes.Enum;
	}
};

module.exports = TimeZone;

TimeZone.Almaty = 0;
TimeZone.Bangkok = 1;
TimeZone.Bombay = 2;
TimeZone.Brasilia = 3;
TimeZone.Cairo = 4;
TimeZone.CapeVerdeIs = 5;
TimeZone.Darwin = 6;
TimeZone.Eniwetok = 7;
TimeZone.Fiji = 8;
TimeZone.HongKong = 9;
TimeZone.Islamabad = 10;
TimeZone.Kabul = 11;
TimeZone.Magadan = 12;
TimeZone.MidAtlantic = 13;
TimeZone.Moscow = 14;
TimeZone.Muscat = 15;
TimeZone.Newfoundland = 16;
TimeZone.Samoa = 17;
TimeZone.Sydney = 18;
TimeZone.Tehran = 19;
TimeZone.Tokyo = 20;
TimeZone.UsAlaska = 21;
TimeZone.UsAtlantic = 22;
TimeZone.UsCentral = 23;
TimeZone.UsEastern = 24;
TimeZone.UsHawaii = 25;
TimeZone.UsMountain = 26;
TimeZone.UsPacific = 27;
TimeZone.Other = 28;
TimeZone.Auckland = 29;
TimeZone.Kathmandu = 30;
TimeZone.EuropeWesternWet = 31;
TimeZone.EuropeCentralCet = 32;
TimeZone.EuropeEasternEet = 33;
TimeZone.Jakarta = 34;
TimeZone.Perth = 35;
TimeZone.Adelaide = 36;
TimeZone.Brisbane = 37;
TimeZone.Tasmania = 38;
TimeZone.Iceland = 39;
TimeZone.Amsterdam = 40;
TimeZone.Athens = 41;
TimeZone.Barcelona = 42;
TimeZone.Berlin = 43;
TimeZone.Brussels = 44;
TimeZone.Budapest = 45;
TimeZone.Copenhagen = 46;
TimeZone.Dublin = 47;
TimeZone.Helsinki = 48;
TimeZone.Lisbon = 49;
TimeZone.London = 50;
TimeZone.Madrid = 51;
TimeZone.Munich = 52;
TimeZone.Oslo = 53;
TimeZone.Paris = 54;
TimeZone.Prague = 55;
TimeZone.Reykjavik = 56;
TimeZone.Rome = 57;
TimeZone.Stockholm = 58;
TimeZone.Vienna = 59;
TimeZone.Warsaw = 60;
TimeZone.Zurich = 61;
TimeZone.Quebec = 62;
TimeZone.Ontario = 63;
TimeZone.Manitoba = 64;
TimeZone.Saskatchewan = 65;
TimeZone.Alberta = 66;
TimeZone.BritishColumbia = 67;
TimeZone.Boise = 68;
TimeZone.Boston = 69;
TimeZone.Chicago = 70;
TimeZone.Dallas = 71;
TimeZone.Denver = 72;
TimeZone.KansasCity = 73;
TimeZone.LasVegas = 74;
TimeZone.LosAngeles = 75;
TimeZone.Miami = 76;
TimeZone.Minneapolis = 77;
TimeZone.NewYork = 78;
TimeZone.NewOrleans = 79;
TimeZone.Phoenix = 80;
TimeZone.SantaFe = 81;
TimeZone.Seattle = 82;
TimeZone.WashingtonDc = 83;
TimeZone.UsArizona = 84;
TimeZone.Chita = 85;
TimeZone.Ekaterinburg = 86;
TimeZone.Irkutsk = 87;
TimeZone.Kaliningrad = 88;
TimeZone.Krasnoyarsk = 89;
TimeZone.Novosibirsk = 90;
TimeZone.PetropavlovskKamchatskiy = 91;
TimeZone.Samara = 92;
TimeZone.Vladivostok = 93;
TimeZone.MexicoCentral = 94;
TimeZone.MexicoMountain = 95;
TimeZone.MexicoPacific = 96;
TimeZone.CapeTown = 97;
TimeZone.Winkhoek = 98;
TimeZone.Lagos = 99;
TimeZone.Riyahd = 100;
TimeZone.Venezuela = 101;
TimeZone.AustraliaLh = 102;
TimeZone.Santiago = 103;
TimeZone.Manual = 253;
TimeZone.Automatic = 254;
