'use strict';

/**
 * timer_trigger enum
 *
 * ****WARNING****  This file is auto-generated!  Do NOT edit this file.
 */

const BaseType = require('../type');

module.exports = class TimerTrigger extends BaseType {
	static getValues() {
		return {
			0: 'manual',
			1: 'auto',
			2: 'fitness_equipment'
		};
	}
}
