'use strict';

/**
 * timer_trigger enum
 *
 * ****WARNING**** This file is auto-generated! Do NOT edit this file.
 */

const BaseType = require('../type');
const FieldTypes = require('../fieldTypes');

const ValuesMap = {
	0: 'manual',
	1: 'auto',
	2: 'fitness_equipment'
};

class TimerTrigger extends BaseType {
	static getValues() {
		return ValuesMap;
	}

	static getSourceType() {
		return FieldTypes.Enum;
	}
};

module.exports = TimerTrigger;

TimerTrigger.Manual = 0;
TimerTrigger.Auto = 1;
TimerTrigger.FitnessEquipment = 2;