'use strict';

/**
 * user_local_id uint16
 *
 * ****WARNING****  This file is auto-generated!  Do NOT edit this file.
 */
module.exports = {
	0: 'local_min',
	15: 'local_max',
	16: 'stationary_min',
	255: 'stationary_max',
	256: 'portable_min',
	65534: 'portable_max'
};
