'use strict';

/**
 * weight uint16
 *
 * ****WARNING****  This file is auto-generated!  Do NOT edit this file.
 */

const BaseType = require('../type');

module.exports = class Weight extends BaseType {
	static getValues() {
		return {
			65534: 'calculating'
		};
	}
}
