'use strict';

/**
 * wkt_step_target enum
 *
 * ****WARNING**** This file is auto-generated! Do NOT edit this file.
 */

const BaseType = require('../type');
const FieldTypes = require('../fieldTypes');

const ValuesMap = {
	0: 'speed',
	1: 'heart_rate',
	2: 'open',
	3: 'cadence',
	4: 'power',
	5: 'grade',
	6: 'resistance'
};

class WktStepTarget extends BaseType {
	static getValues() {
		return ValuesMap;
	}

	static getSourceType() {
		return FieldTypes.Enum;
	}
};

module.exports = WktStepTarget;

WktStepTarget.Speed = 0;
WktStepTarget.HeartRate = 1;
WktStepTarget.Open = 2;
WktStepTarget.Cadence = 3;
WktStepTarget.Power = 4;
WktStepTarget.Grade = 5;
WktStepTarget.Resistance = 6;