'use strict';

/**
 * wkt_step_target enum
 *
 * ****WARNING****  This file is auto-generated!  Do NOT edit this file.
 */
module.exports = {
	0: 'speed',
	1: 'heart_rate',
	2: 'open',
	3: 'cadence',
	4: 'power',
	5: 'grade',
	6: 'resistance'
};
