'use strict';

/**
 * workout_power uint32
 *
 * ****WARNING****  This file is auto-generated!  Do NOT edit this file.
 */

const BaseType = require('../type');

const ValuesMap = {
	1000: 'watts_offset'
};

module.exports = class WorkoutPower extends BaseType {
	static getValues() {
		return ValuesMap;
	}
};
