'use strict';

/**
 * workout_hr uint32
 *
 * ****WARNING****  This file is auto-generated!  Do NOT edit this file.
 */

const BaseType = require('../type');

module.exports = class WorkoutHr extends BaseType {
	static getValues() {
		return {
			100: 'bpm_offset'
		};
	}
}
