'use strict';

/**
 * workout_power uint32
 *
 * ****WARNING****  This file is auto-generated!  Do NOT edit this file.
 */

const BaseType = require('../type');

module.exports = class WorkoutPower extends BaseType {
	static getValues() {
		return {
			1000: 'watts_offset'
		};
	}
}
