'use strict';

const cases = require('./cases');
const fs = require('fs');
const path = require('path');

const XLSX = require('./xlsx');

const targetTypesPath = path.resolve(__dirname, '../types');

const alertHeader = '****WARNING**** This file is auto-generated! Do NOT edit this file.';

const fieldMap = require('./fieldMap');

const FieldTypes = require('../fieldTypes');
const processMessages = require('./process/messages');
const processTypes = require('./process/types');

const fieldTypesNames = { };

Object.keys(FieldTypes).forEach(key => {
	fieldTypesNames[FieldTypes[key]] = key;
});

function parseTypes(sheet) {

}

module.exports = function(profilePath) {
	const workbook = new XLSX(profilePath);

	const types = processTypes(workbook.sheet('Types'));

	if (undefined === types['mesg_num']) {
		throw new Error('Message numbers type not found');
	}

	const messageTypes = { };
	types['mesg_num'].values.forEach(value => {
		messageTypes[value.name] = value.value;
	});

	processMessages(workbook.sheet('Messages'), messageTypes);
};
